name: cron_job

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 */2 * * *'  # Runs every 2 hours
  workflow_dispatch:  # Allows manual trigger from the Actions tab

jobs:
  test_job:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World
        run: echo "Hello World from GitHub Actions"
