name: cron_job

# Controls when the workflow will run
on:
  # cron job every 2 hours
  schedule:
   - cron: '*/1 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World Step
        run: echo "Hello World from GitHub Actions!"
